import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "../components/Footer";
import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Pacifico&family=Lobster&family=Orbitron:wght@500&family=Dancing+Script:wght@700&display=swap" rel="stylesheet" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ position: "relative", minHeight: "100vh", overflowX: "hidden" }}
      >
        {/* Background YouTube Video */}
        <div style={{
          position: "fixed",
          top: 0,
          left: 0,
          width: "100vw",
          height: "100vh",
          minWidth: "100vw",
          minHeight: "100vh",
          maxWidth: "100vw",
          maxHeight: "100vh",
          zIndex: 0,
          overflow: "hidden",
          pointerEvents: "none"
        }}>
          <iframe
            width="100vw"
            height="100vh"
            style={{
              position: "absolute",
              top: 0,
              left: 0,
              width: "100vw",
              height: "100vh",
              minWidth: "100vw",
              minHeight: "100vh",
              maxWidth: "100vw",
              maxHeight: "100vh",
              objectFit: "cover",
              zIndex: 0,
              pointerEvents: "none"
            }}
            src="https://www.youtube.com/embed/9_FQW36r0n8?autoplay=1&mute=1&loop=1&playlist=9_FQW36r0n8&controls=0&showinfo=0&modestbranding=1&rel=0"
            title="Background Video"
            frameBorder="0"
            allow="autoplay; encrypted-media"
            allowFullScreen
          />
        </div>
        {/* Main Content Overlay */}
        <div style={{ position: "relative", zIndex: 1, minHeight: "100vh", display: "flex", flexDirection: "column" }}>
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
